#!/usr/bin/env bash

~/.config/tmux/set-last-window-index
selected_name=$(echo $(basename $(pwd)) | sed "s/^./_/")
tmux_running=$(pgrep tmux)
if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
	tmux new-session -s $selected_name -c .
	tmux rename-window $selected_name
	exit 0
fi

~/.config/tmux/tmux-sessionizer
