#!/usr/bin/env bash

touch ~/.last_tmux_window_index
tmux_running=$(pgrep tmux)
if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
	exit 0
fi
echo "$(tmux display-message -p '#{window_index}')" >~/.last_tmux_window_index
