#!/usr/bin/env bash

[ "$(tmux ls | sed "s/:.*$//" | grep "^$(basename $1)$")" != "" ] &&
	basename $1 |
	sed "s/^\./_/" |
		xargs -I{} echo $([ "$(tmux display-message -p '#S')" != "$(basename $1 | sed 's/^\./_/')" ] && echo {} || echo "{}:$(cat ~/.last_tmux_window_index)") |
		xargs -I{} tmux capture-pane -ep -t {}
