#!/usr/bin/env bash

if [[ ! -f ~/.tmux-repo ]]; then
  echo "~/.tmux-repo file not found"
  exit 0
fi

to_find_path=$(echo $(sed "s|~|$HOME|g" ~/.tmux-repo | tr -s '\n' ' '))

search_paths=$(find $to_find_path -mindepth 0 -maxdepth 2 -type d -exec [ -e '{}/.git' ] ';' -prune -print)

selected=$(echo ${search_paths[@]} | tr ' ' '\n' | fzf --preview "~/.config/tmux/tmux-preview {}")

if [[ -z $selected ]]; then
  exit 0
fi

if [[ ! -d $selected ]]; then
  echo "$selected not found"
  exit 0
fi

selected_name=$(basename "$selected" | tr . _)

if ! tmux has-session -t=$selected_name 2>/dev/null; then
  tmux new-session -ds $selected_name -c $selected
fi

tmux list-sessions -F '#{session_attached}' | grep -q 1 && tmux switch-client -t $selected_name || tmux attach-session -t $selected_name
