#!/usr/bin/env bash

tmux rename-window tmux-clear

current_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

toClearSession=$(tmux ls | sed "s/:.*$//" | fzf -m --preview "$current_dir/tmux-preview {}")

if [[ -z $toClearSession ]]; then
	exit 0
fi

for session in $toClearSession; do
	tmux kill-session -t $session
	echo "Session $session cleared"
done
