#!/usr/bin/env bash

toClearSession=$(tmux ls | sed "s/:.*$//" | fzf -m --preview 'tmux capture-pane -ep -t {}')

if [[ -z $toClearSession ]]; then
	exit 0
fi

for session in $toClearSession; do
	tmux kill-session -t $session
	echo "Session $session cleared"
done
