[ env ]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
opacity = 0.2
blur = true

decorations = "Buttonless"
startup_mode = "Maximized"


[font]
normal.family = "FiraCode Nerd Font"

#regular
size = 24

#for video
# size = 35.0
